import type {IdentityRuntime} from '../identity/IdentityRuntime';
import type {PairingRuntime} from '../identity/PairingRuntime';
import type {QrScannerRuntime} from '../capability/QrScannerRuntime';
import type { ProviderSettings } from './ProviderSettings';
import type { SessionRuntime } from './SessionRuntime';
import type { ChatRuntime } from '../chat/ChatRuntime';
import type { ModelInfo } from '../../domain/model/ModelProvider';
import type { MemoryRuntime } from '../memory/MemoryRuntime';
import type { ChatMemoryExtraction } from '../memory/ChatMemoryExtraction';
import type {CapabilityRuntime} from '../capability/CapabilityRuntime';
import type {CapabilityAuditSink} from '../../domain/capability/CapabilityAudit';
import type {TaskRuntime} from '../task/TaskRuntime';
import type {ApprovalRuntime} from '../task/ApprovalRuntime';
import type {PushAttentionRuntime} from '../task/PushAttentionRuntime';
import type {SyncQueueRuntime} from '../sync/SyncQueueRuntime';
import type {OfflineInboxRuntime} from '../inbox/OfflineInboxRuntime';
import type {ShareIngressRuntime} from '../inbox/ShareIngressRuntime';
import type {VoiceRuntime} from '../voice/VoiceRuntime';
import type {ActionCenterRuntime} from '../event/ActionCenterRuntime';
import type {BackgroundCatchupRuntime} from '../sync/BackgroundCatchupRuntime';
import type {ExtensionInstallRuntime} from '../extension/ExtensionInstallRuntime';
import type {ExtensionLifecycleRuntime} from '../extension/ExtensionLifecycleRuntime';
import type {ExtensionImportRuntime} from '../extension/ExtensionImportRuntime';
import type {PreferencesRuntime} from './PreferencesRuntime';
import type {UpdateService} from '../../domain/update/UpdateService';
export interface MobileServices {
  appVersion?: string;
  updates?: UpdateService;
  capabilityRuntime: CapabilityRuntime;
  capabilityAudit?: CapabilityAuditSink;
  tasks: TaskRuntime;
  approvals: ApprovalRuntime;
  pushAttention: PushAttentionRuntime;
  syncQueue: SyncQueueRuntime;
  inbox: OfflineInboxRuntime;
  shareIngress: ShareIngressRuntime;
  voice: VoiceRuntime;
  actionCenter: ActionCenterRuntime;
  backgroundCatchup: BackgroundCatchupRuntime;
  extensionInstall?: ExtensionInstallRuntime;
  extensionLifecycle?: ExtensionLifecycleRuntime;
  extensionImport?: ExtensionImportRuntime;
  identity?: IdentityRuntime;
  pairing?: PairingRuntime;
  qrScanner?: QrScannerRuntime;
  memory: MemoryRuntime;
  memoryExtraction: ChatMemoryExtraction;
  settings: ProviderSettings;
  preferences: PreferencesRuntime;
  sessions: SessionRuntime;
  chat: ChatRuntime;
  reloadProviders(): Promise<void>;
  listModels(id: string): Promise<ModelInfo[]>;
  close(): Promise<void>;
}
